### ISSUE TITLE
Estudar tipos de testes

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#118]
## Descrição

- Estudar quais tipos de testes de software existem, para colocarmos no projeto e ter uma integração continua

## Tarefas

- [x] Estudar que tipos de testes existem
- [x] Fazer um resumo ao grupo

## Critério de aceitação
- [ ] Todos comentarem algo sobre o aprendizado.
- [x] Apresentar fontes dos estudos
- [x] Falar no mínimo do teste unitário

**Comment by ciro-c** [comment]
## Testes unitários e de integração.

### Testes unitários

Descrição: É a forma de se testar unidades individuais de código fonte. Unidades podem ser métodos, classes, funcionalidades, módulos, etc. Depende muito do que é a menor parte que seu Software pode ser testado.

Objetivo: dos testes unitários é mostrar que cada unidade atende corretamente sua especificação.

Exemplo: testes automáticos criados para darem entradas e conferirem saídas a cada método, permitindo que se saiba que está funcionando de acordo com o esperado.

Benefícios: encontrar problemas o quanto antes, facilitam a mudança da unidade, simplificam a integração e melhoram a documentação.

### Testes de Integração

Descrição: É a forma de se testar a combinação das unidades em conjunto.

Objetivo: Nesse caso, a ideia é encontrar falhas na junção destas unidades. Pode ser que a classe X funcione bem sozinha, mas ao ser utilizada pela classe Y, ela deixe de funcionar.

Exemplo: Colocar todo o software para rodar e começar a usar diversas funcionalidades consideradas centrais no seu programa para confirmar que ele roda e as principais funcionalidades fazem o esperado.

Benefícios: além de testar funcionalmente, pode assegurar performance e confiabilidade. Ajudam a garantir que o trabalho de um desenvolvedor não está afetando o trabalho de outro e em equipes grandes isso pode fazer toda a diferença se forem realizados com frequência.

[Fonte 1](https://pt.stackoverflow.com/questions/115146/qual-a-diferen%C3%A7a-entre-teste-unit%C3%A1rio-e-teste-integrado#:~:text=Descri%C3%A7%C3%A3o%3A%20%C3%89%20a%20forma%20de,unidade%20atende%20corretamente%20sua%20especifica%C3%A7%C3%A3o.)

[Fonte de possíveis pacotes para testes](https://medium.com/assertqualityassurance/teste-unit%C3%A1rio-e-qualidade-de-software-acce7b9c537)

**Comment by ciro-c** [comment]
## Outra classificação de testes que achei

### Teste de usabilidade

O teste de usabilidade é de suma importância para avaliar a qualidade do software no quesito experiência do usuário. A finalidade é compreender o quão intuitivo, compreensível e inteligível é a interface do programa para o usuário final.

Nesse caso, é fundamental a compreensão de como o software será utilizado. Por exemplo: nem sempre a aplicação é executada em primeiro plano, o que leva a equipe a construir uma interface que permaneça agradável quando redimensionada.

Além disso, como os perfis de usuário variam a cada projeto, o teste de usabilidade é realizado com esses grupos de pessoas, de modo que elas opinem acerca da facilidade de uso, das questões visuais (cores, fontes, poluição visual etc.), entre outros detalhes que prejudicam a experiência de uso.

### Testes funcionais

O teste funcional consiste em uma série de subtestes (técnicas), cujo objetivo é atestar se a aplicação é capaz de desempenhar as funções que se propõe a fazer. As técnicas mais comuns englobadas pelo teste funcional são os testes denominados caixa-branca e caixa-preta.

O teste de caixa-branca tem como foco a análise do comportamento interno do software, ou seja, o seu código-fonte. Já o teste de caixa-preta é feito em cima das funções que devem ser desempenhadas pelo programa.

### Teste de integração

Entre os principais tipos de teste de software está o teste de integração. A finalidade dele é analisar o comportamento do software quando interage com outras aplicações ou processos. Há diversas situações em que os testes de integração se mostram úteis — quando o software se comunica com um banco de dados ou servidor que estabelece a conexão dele com a internet, por exemplo.

A ideia é compreender se o processo em questão gera alguma falha/instabilidade. O mesmo vale para aplicações a serem utilizadas em cooperação pelo usuário final.


### Testes de performance

Os testes de performance são uma série de análises voltadas para o desempenho do software mediante várias situações. A partir dos diagnósticos, a equipe é capaz de compreender os limites do programa sob diversas condições.

Para constatar a qualidade da aplicação, ela é submetida a avaliações que simulam eventos e situações previsíveis de acordo com a rotina do cliente, ou seja, testes de carga, estresse e estabilidade. Quaisquer falhas detectadas durante o teste são corrigidas pela equipe precisa e cirurgicamente.

### Testes de carga e estresse

Você sabia que o software, assim como o hardware, pode apresentar problemas quando recebe cargas altas de processos e requisições? Isso acontece justamente para mensurar se as condições nas quais ele será submetido não vão comprometer o seu desempenho.

Contudo, imprevisivelmente, a sobrecarga pode acontecer durante a utilização, gerando o que chamamos “estresse”. Como descobrir o nível de tensão capaz de levar o software a parar de funcionar? Nesse caso, é executado o teste de estresse, que consiste em simular eventos de carga excessiva, forçando o software ao extremo.

### Teste de estabilidade

A partir do momento em que se planeja construir um software para o cliente, é necessário que o produto final apresente certa estabilidade, condizente com a carga de trabalho a ser suportada diariamente. O ideal, evidentemente, é que o software não sofra perda de performance depois de determinado tempo de uso.

### Teste de regressão

Como o próprio nome diz, o teste de regressão é uma metodologia usada, entre outras coisas, para evitar a recorrência de um erro. Um exemplo comum de sua aplicação é quando o programador modifica o código — seja para eliminar um bug, seja para acrescentar funcionalidades — e procura identificar falhas até então inexistentes.

Esse tipo de comprometimento pode acontecer em função de problemas previamente corrigidos em uma versão anterior. Sabe quando um sistema passa por um update e, assim que as atualizações são instaladas, fica instável? Pois bem, o teste de regressão é essencial para impedir esse tipo de situação.

### Teste de segurança

Por sua vez, o teste de segurança é um dos mais importantes da lista, sobretudo quando falamos em software corporativo. Afinal, a proteção dos dados é imprescindível a toda e qualquer empresa que armazena informações no ambiente virtual — que é repleto de ameaças.

Esse teste é realizado por uma equipe especializada em Segurança da Informação, incumbida de avaliar se há brechas de segurança a partir de procedimentos, tais como análise de vulnerabilidade, coleta de informações e violação de senha.

Dessa maneira, o produto final só é entregue ao cliente quando os requisitos de segurança são devidamente preenchidos, garantindo à empresa que suas informações ficarão protegidas contra invasão cibernética.

[Fonte](https://blog.cronapp.io/tipos-de-teste-de-software/)

**Comment by ErickMVdO** [comment]
Entendi que os tipos de testes são necessários para nos informar que cada parte do código, assim como ele completo, está funcionando corretamente.

**Comment by carlinhos-pinheiro** [comment]
Testes são práticas usadas especialmente para proteger código em produção. Os testes unitário validam as funções atômicas do código, assim como existem os teste de integração e testes de sistemas, que validam o código por completo.
Por meio dos testes, métodos que eventualmente estariam quebrados não sobem para deploy e garantem um produto de mais qualidade, quanto mais fortes forem os testes, mais protegido o produto final estará.
Para o backend, existe uma ótima biblioteca para testes chamada de Jest.js, e acredito que seria bom usarmos ela.
