### ISSUE TITLE
Estudar fluxo de Integração continua

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#119]
## Descrição

- Estudar Integração Continua (CI) para aplicar ao projeto e facilitar a entrega

## Tarefas

- [x] Estudar fluxo de uma CI
- [x] Estudar o que é necessário para aplicar uma CI no projeto
- [x] Fazer um resumo ao grupo

## Critério de aceitação
- [ ] Todos comentarem algo sobre o aprendizado.
- [x] Apresentar as fontes

**Comment by GRVial** [comment]
Integração contínua é um método de desenvolvimento em que o time de programadores implementam frequentemente em uma branch que é testada, facilitando a detecção de erros ou bugs.

### Links para estudo:
- [link 1](https://www.cloudbees.com/continuous-delivery/continuous-integration)
- [link 2](https://www.thoughtworks.com/continuous-integration)

**Comment by ciro-c** [comment]
## O que é CI ( integração continua)
  A integração contínua é um termo originado na metodologia ágil XP e utilizado em diversas metodologias, consistindo em algo simples: o desenvolvedor integra o código alterado e/ou desenvolvido ao projeto principal na mesma frequência com que as funcionalidades são desenvolvidas, sendo feito muitas vezes ao dia ao invés de apenas uma vez. O objetivo principal de utilizar a integração contínua é verificar se as alterações ou novas funcionalidades não criaram novos defeitos no projeto já existente. A prática da integração contínua pode ser feita através de processos manuais ou automatizados, utilizando ferramentas como o Jenkins, Hudson entre outros.
## Para que?
  Agilizar o código. ~~Só tem bug se o cliente achar~~
 ## O que precisamos?
 - Testes , de todos os tipos. Precisamos que eles rodem localmente, no computador do desenvolvedor, e remotamente, no repositório.
- Repositório com ações ou *pluggins*, é nele que colocaremos os testes remotos
 ## Lado bom
 Agiliza a produção do código, e a quantidade de *features* entregues.
 ## Lado ruim
 Se não quebrar o código, alguém pode colocar malwares no código.
 
 Fontes
 [Link 1](https://www.devmedia.com.br/integracao-continua-uma-introducao-ao-assunto/28002)
 [Link 2](https://aws.amazon.com/pt/devops/continuous-integration/#:~:text=A%20integra%C3%A7%C3%A3o%20cont%C3%ADnua%20%C3%A9%20uma,cria%C3%A7%C3%B5es%20e%20testes%20s%C3%A3o%20executados.)

**Comment by ErickMVdO** [comment]
Pelo que eu entendi, integração contínua, em relação ao nosso projeto, seria criar uma funcionalidade como validar o nome, por exemplo, e em seguida já integrá-la ao código principal, porque desse modo o código é produzido mais rapidamente.

**Comment by carlinhos-pinheiro** [comment]
Antigamente no desenvolvimento de software, o deploy de um sistema era algo doloroso, por isso os desenvolvedores evitavam ao máximo fazer-lo. No entanto, essa prática não era ágil. Com o surgimento do Dev-ops, também veio a integração contínua, que seria o hábito de agregar à produção todas eventuais modifições a medida que essa eram implementadas. 
Desse modo, são mais deploys com massa de código menores, ao contrário de antes: poucos deploys com massas de códigos gigantes e difíceis de debugar.
Para a integração contínua funcionar, é preciso ter muito testes de qualidade para garantiar um produto funcional.

**Comment by PauloAbiAcl** [comment]
Integração contínua é uma prática que os desenvolvedores, estão sempre juntando pequenas partes de código no repositório, tornando a produção mais rápida.
