### ISSUE TITLE
Decidir Tecnologias para o projeto

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#12]
## Descrição

Debater e escolher que tecnologias iremos usar no mobile e no back-end

## Critério de aceitação

- [x] Maioria aceitar

**Comment by carlinhos-pinheiro** [comment]
Eu voto por react-native pro mobile, node.js pro backend e mongoDB para o banco da dados. Os três têm uma integração muito forte e usam Javascript. A curva de aprendizado é menor.

**Comment by KaduRoriz** [comment]
eu faço das palavras do Carlos as minhas, além do que ele disse acredito que é mais fácil achar material para estudar a respeito dessas tecnologias, inclusive vai ter uma NLW começando no dia 28 (sei que eles não vão muito a fundo mas já ajuda)

**Comment by ciro-c** [comment]
Eu voto por Flutter, tem sintaxe parecida com a do JS e se apresenta mais simples de construir aplicações que o React Native, alêm de apresentar uma performance [maior.](https://www.youtube.com/watch?v=MbftjVCb3j8)
Não precisamos construir site então o react Native site é algo desnecessario

**Comment by carlinhos-pinheiro** [comment]
Por mim usar Flutter também vai ser legal. Eu nunca usei a tecnologia mas tenho interesse em aprender.

**Comment by carlinhos-pinheiro** [comment]
Em reunião decidimos usar o Flutter no front-end devido ao seu desempenho, simplicidade e indepedência de pacotes externos. Para o backend usaremos o Node.js e o MongoDB, visto que uma boa parte do grupo conhece a tecnologia e o mongoDB é um banco de dados não-relacional com forte integração ao Node.JS.
