### ISSUE TITLE
Atualizar Backlog

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#134]
## Descrição

Atualizar o backlog.

## Tarefas

- [x] Colocado a feature de recuperar senha 
- [x] Corrigir possiveis erros

## Critério de aceitação

- [x] Ter uma nova versão
- [x] Ter colocado a feature de recuperar senha

**Comment by carlinhos-pinheiro** [comment]
Além de recupar senha, deveria mudar algo mais?
