### ISSUE TITLE
Decidir o nome do app

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#14]
## Descrição

Debater e decidir o nome do app

**Comment by carlinhos-pinheiro** [comment]
Carteira de Vacina

**Comment by PauloAbiAcl** [comment]
Pensei em Minhas Vacinas, mas pesquisei e vi que já existe.

**Comment by ciro-c** [comment]
Vacina-E

**Comment by carlinhos-pinheiro** [comment]
e-vacina

**Comment by carlinhos-pinheiro** [comment]
Por votação foi decidido que vai ser e-Vacinas/e-Vacina.
