### ISSUE TITLE
Criar tela de ajuda

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#146]
## Descrição

Criar tela de ajuda

## Tarefas

- [x] Criar a tela de ajuda de acordo com o protótipo
- [x] Criar os dropdown

## Critério de aceitação

- [x] Ter criado a ela de acordo como protótipo
- [x] Dropdown funcionando e com informações corretas

**Comment by ErickMVdO** [comment]
Os dropdowns que eu encontrei pesquisando tinham apenas opção de selecionar o valor desejado, e não era isso que queremos, mas sim apenas mostrar os textos, então eu criei containers que funcionam dessa forma.
