### ISSUE TITLE
Adicionar variaveis de ambiente

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#147]
## Descrição

Adicionar variáveis de ambiente ao repositorio, e apagar a pasta `config`

## Tarefas

- [x] Instalar Dotenv
- [x] Fazer um .env.example
- [x] Fazer as alterações no codigo para utilizar as variáveis
- [x] Apagar a pasta `config`
- [x] Criar um arquivo no drive do projeto com as variaveis

## Critério de aceitação

- [x] Ter criado o arquivo no drive do projeto com as variaveis
- [x] Ter apagado a pasta `config`
- [x] Ter feito um .env.example
- [x] As variáveis de ambiente estarem funcionando

**Comment by ciro-c** [comment]
[Link](https://blog.rocketseat.com.br/variaveis-ambiente-nodejs/) que pode ajudar

**Comment by carlinhos-pinheiro** [comment]
Não sei muito bem o que colocar no .env.example do nosso projeto por enquanto.
