### ISSUE TITLE
Instalar Docker

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#15]
## Descrição

Instalar o docker no computador

**Comment by carlinhos-pinheiro** [comment]
Instalado!

**Comment by KaduRoriz** [comment]
instalado ^

**Comment by ErickMVdO** [comment]
Instalado

**Comment by PauloAbiAcl** [comment]
Instalado

**Comment by ciro-c** [comment]
o meu ja esta instalado

**Comment by carlinhos-pinheiro** [comment]
Como aparentemente falta só uma pessoa para instalar, acho que já podemos fechar a issue.
