### ISSUE TITLE
Fazer deploy back-end

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#169]
## Descrição

Fazer deploy do back-end no heroku

## Tarefas

- [x] Fazer deploy do back-end no heroku
- [x] Configurar como CD(continuos Deployment)

## Critério de aceitação

- [x] Ter feito o deploy no heroku
- [x] CD estar funcionando
- [x] Conseguir acessar publicamente

**Comment by carlinhos-pinheiro** [comment]
O deploy foi feito no horuko. O workflow de CD está na minha branch para conferir.
Acesse publicamente: https://e-vacina-backend.herokuapp.com/user
