### ISSUE TITLE
Criar ambiente Node.js

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#18]
## Descrição

Configurar o ambiente para desenvolvimento em Node.js

## Tarefas

- [x] Back-End: Configurar o ambiente para o Node

## Critério de aceitação

- [x] Back-End estar com o Node instalado.
- [x] Back-End estar com o Mongodb
- [x] Back-End estar com o Nodemon

**Comment by KaduRoriz** [comment]
arquivo JS

![Screenshot from 2021-02-23 22-39-08](https://user-images.githubusercontent.com/77363425/108933318-b194fc80-7629-11eb-9d45-70eb726ee2df.png)

arquivo Dockerfile

![Screenshot from 2021-02-23 22-40-00](https://user-images.githubusercontent.com/77363425/108933381-d12c2500-7629-11eb-9845-4e1f1857b402.png)

INSTRUÇÕES PARA O DOCKERFILE

FROM NODE:ALPINE // o node vai fazer com que o docker pegue a última versão do node e o alpine vai utilizar a versão alpine das máquinas, uma versão reduzida das máquinas só com o node

WORKDIR Document/MDS //aqui estou decidindo o diretório que quero trabalhar na minha máquina com o docker

COPY package*.json ./   //aqui estou copiando todos os arquivos .json pra dentro da minha pasta MDS

RUN npm install 

COPY . . /após dar o run npm install eu posso copiar todo o restando dos arquivos para o docker

fazendo isso, a pasta node_modules não é necessária passar para o Docker pois com o COPY . . já estará no Docker, então vamos ignorar a node_ module colocando no arquivo.dockerignore colocar o node_modules dentro.

EXPOSE 3000 // o expose mostra para o servidor docker qual porta ele deve utilizar

CMD [“npm”, “start”] // propriedade que indica qual comando  para startar o servidor


sudo docker build -t nomedoseucontainer/diretorioOndetáODockerfile

docker run -p 3000:3000 -d //informando que quando eu acessar no navegador a porta 3000 eu quero acessar a a porta 3000 do container


package.json

![Screenshot from 2021-02-23 22-53-46](https://user-images.githubusercontent.com/77363425/108933513-09cbfe80-762a-11eb-8c46-e54702953255.png)



Vou fazer o do mongodb igual a esse aqui também

Aqui vai vídeo da ambientação do docker e do mongodb:

https://www.youtube.com/watch?v=AVNADGzXrrQ

https://www.youtube.com/watch?v=NX46vz9cujE

**Comment by carlinhos-pinheiro** [comment]
Como separamos o projeto em dois repositórios, vou criar uma issue relacionada ao ambiente de Flutter no repositório de Frontend.

**Comment by KaduRoriz** [comment]
A parte do mongodb no docker é muito mais processos no terminal, então acho vou deixar só um vídeo aqui que eu achei que serviu para mim: https://www.youtube.com/watch?v=uklyCSKQ1Po apesar do sotaque dele atrapalhar um pouco o entendimento eu achei ele bem sucinto, caso não manje de inglês tem esse aqui: https://www.youtube.com/watch?v=4QiH0C9_9pU , e tem esse site aqui mostrando passo a passo também: https://terminalroot.com.br/2020/02/mongodb.html

obs: Alguns comandos pode dar um errinho falando que teve acesso negado ou coisa do tipo, caso de na maquina de vocês também usem o sudo antes do comando para gerenciar como o usuário principal e dar acesso geral
