### ISSUE TITLE
Criar templates issues

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#37]
## Histórico de Versões
| Versão  |  Data  | Autor  |  Descrição  |
| ------------------- | ------------------- | ------------------- | ------------------- |
|  1.0 |  2/03/2020 | Ciro | Criar Issue templates |

## Descrição

Criar mais templates de issues para a documentação do projeto, possiveis duvidas, falhas de segurança encontradas, e melhorar um codifo(refatorar), criar issue de estudo.

## Tarefas

- [x] Criar template de issue de Documentação
- [x] Criar template de issue de Dúvida
- [x] Criar template de issue de Falha de segurança
- [x] Criar template de issue de Melhorar uma funcionalidade
- [x] Criar template de issue de Discussão
- [x] Criar template de isseu de Estudo

## Critério de aceitação

- [x] Ter criado template de issue de Documentação
- [x] Ter criado template de issue de Dúvida
- [x] Ter criado template de issue de Falha de segurança
- [x] Ter criado template de issue de Discussão
- [x] Ter criado template de issue de Melhorar uma funcionalidade
- [x] Ter criado template de issue de Estudo

**Comment by carlinhos-pinheiro** [comment]
Eu faço os templates para dúvida e falha de segurança.

**Comment by PauloAbiAcl** [comment]
To fazendo os templates de estudo e documentação.

**Comment by KaduRoriz** [comment]
Fiz o pull request das duas tempaltes designadas a mim ! ^^
