### ISSUE TITLE
Estudar tipos de elicitação de requisitos

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#45]
## Histórico de Versões
| Versão  |  Data  | Autor  |  Descrição  |
| ------------------- | ------------------- | ------------------- | ------------------- |
|  1.0 |  3/03/2020 | Ciro | Issue template |

## Descrição

Estudar os tipos de elicitação de requisitos e trazer material de estudo resumido para o grupo.

**Comment by GRVial** [comment]
## Elicitação de requisitos

A elicitação de requisitos é a etapa de um projeto na qual se visa conhecer e entender as necessidades e desejos do público alvo do produto, que serão traduzidas em funcionalidades implementadas na solução final.

### Links para estudo das técnicas de elicitação:
[link1](https://sites.google.com/site/tecnicaselicitacao/#:~:text=Essa%20t%C3%A9cnica%20consiste%20em%20reuni%C3%B5es,o%20sistema%20que%20ser%C3%A1%20desenvolvido)
[link2](https://www.devmedia.com.br/tecnicas-para-levantamento-de-requisitos/9151)
