### ISSUE TITLE
Olhar os documentos de visão dos projetos passados

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#5]
#O que tem que fazer

- [x] Olhar documentos de visão dos projetos passados
- [x] Dar um resumo para o grupo sobre o que é

**Comment by PauloAbiAcl** [comment]
O documento de visão mostra de forma simples e objetiva o problema, solução e os recursos de alto nível do produto, com o objetivo de fornecer uma visão ampla do produto sem se ater a detalhes. Facilita uma análise inicial e evita duvidas entre os envolvidos no projeto

Link que da uma breve explicação:
https://www.ibm.com/support/knowledgecenter/pt-br/SSWMEQ_4.0.6/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html

**Comment by PauloAbiAcl** [comment]
Alguns bons exemplos de documento de visão:
https://fga-eps-mds.github.io/2018.2-ComexStat/docs/docVisao
https://fga-eps-mds.github.io/2019.2-Acacia/#/vision_document
https://fga-eps-mds.github.io/2020.1-Minacademy-Wiki/documentos/doc_visao/
