### ISSUE TITLE
Melhorias de UX/UI e Desing

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#51]
## Histórico de Versões
| Versão  |  Data  | Autor  |  Descrição  |
| ------------------- | ------------------- | ------------------- | ------------------- |
|  1.0 |  4/03/2020 | Ciro | Melhorias UX/UI e desing geral |

## Descrição

  Escreva nos comentários melhorias a ser feitas no desing, ux, ui do projeto, docs, githubpages.
  Os comentários tem que ter um checkbox  

- [ ]  ` - [ ] ` e a descrição da alteração.

Ex:
 - [x] Arrumar o botão da página inicial.
 
 Como foi escrito:
 `- [ ] Arrumar o botão da página inicial`

**Comment by ciro-c** [comment]
- [x] Arrumar a página inicial do githubpages

**Comment by ciro-c** [comment]
- [ ] Fazer um read.me legal para back e front

**Comment by GRVial** [comment]
- [x] Escolher um tema agradável
- [x] Botão de acesso ao repositório
- [x] Adicionar sidebar

**Comment by KaduRoriz** [comment]
Acho que talvez criar até uma branch separada para docs
