### ISSUE TITLE
Decidir temas para o projeto

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#6]
#O que tem que fazer

- [x] arrumar 3 temas e colocar na planilha

**Comment by carlinhos-pinheiro** [comment]
**Temas/Projetos que vieram na minha cabeça:**

- Aplicativo para adoções de pets.
- Plataforma para aplicação de provas na UnB.
- Construir interface bonita para o CDMOJ.

**Comment by carlinhos-pinheiro** [comment]
**Mais temas/projetos:**

- Aplicativo para editar fotos.
- Plataforma para realizar simulados do Pas/Enem com questões de edições antigas. Além de realizar o simulado, a plataforma daria insights e feedbacks em relação ao desempenho do aluno.

**Comment by ggomesbr** [comment]
****Temas que pensei:

- carteira de vacinação digital, que armazenaria as vacinas tomadas, data, lote, etc.
- app para economia doméstica para fazer lista de compras e controlar preços de marcadorias em mercados diferentes, plotando gráficos para o acompanhamento dos preços dos produtos, armazenar contas de água e de luz, etc.

**Comment by ciro-c** [comment]
Apk mostrando veterinario proximos

**Comment by KaduRoriz** [comment]
Um site que cria lojinhas online, tipo, eu sou vendedor de cueca ai eu quero fazer um site pra vender minhas cueca... seria tipo um wix só que só de loja

**Comment by KaduRoriz** [comment]
Um tinder pra pet, onde você coloca seu cachorro e procura uma pretendente pra ele kkkk

**Comment by ErickMVdO** [comment]
Um jogo 2d de puzzles
