### ISSUE TITLE
Estudar os tipos de arquitetura de software

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#7]
#O que fazer

- [x] estudar os tipos de arquitetura de software que existem
- [x] apresentar para o  grupo um resumo sobre o que é

**Comment by carlinhos-pinheiro** [comment]
A arquitetura de um software é uma representação abstrata dos seus componentes fudamentais, suas propiedades e como eles se comunicam. Por meio dessa representação, é possível enteder o comportamento de um sistema sem acessar seu código fonte. Basicamente a arquitera seria a _blueprint_ do software.
Ao escolher uma arquitetura, escolhas estruturais importantes são feitas, visto que é muito caro voltar atrás nessa decições durante a fase de desenvolvimento. 
Normalmente, o design é representado por meio de um diagrama, semelhante a um diagrama de classes.[
![1why-architectural-diagrams-2-1547639071547](https://user-images.githubusercontent.com/49319516/107278712-e4899e80-6a34-11eb-8347-89b03f92ab64.jpg)
](url)

**Comment by carlinhos-pinheiro** [comment]
[https://techbeacon.com/app-dev-testing/top-5-software-architecture-patterns-how-make-right-choice](url)

[https://towardsdatascience.com/10-common-software-architectural-patterns-in-a-nutshell-a0b47a1e9013](url)

[https://youtu.be/_07NtoK-Kns](url)

Segue dois links que dão uma breve explicação dos tipos mais comuns de arquitetura de software. Também uma aula no youtube explicando o básico.
