### ISSUE TITLE
Estudar Git Flow

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#8]
#O que fazer

- [x] Estudar o que é git flow
- [x] Apresentar para o grupo o que é

**Comment by KaduRoriz** [comment]
Git Flow é um modelo, uma estratégia, utilizada por equipes de desenvolvimento de software que ajudam na organização de versionamento do código, essa estratégia melhora a organização das Branchs dentro do repositório.

Nesse modelo a Branch é como uma ramificação, assim esse modelo pode ser enxergado como uma árvore e seus galhos. Esse modelo trás uma solução para projetos os quais são bem encorpados que precisam sofrer novas atualizações constantemente e projetos onde há muitas pessoas fazendo novos commits. Nesse modelo, há duas tipos de Branchs, a MASTER onde se encontram as branchs principais e a DEVELOP onde se encontram as branchs de suporte: features, release e hotfix.

O fluxo do git flow funciona assim:

Temos a Branch master que continua sendo utilizada para enviar os commits dos releases para a produção. A partir da da Master é criada a branch DEVELOP que conterá todas as novas features estáveis que serão mergeadas (juntar) numa branch de release. A partir da Develop são criadas as Features, para cada nova Features, uma branch nova é criada, a Feature poderá voltará para a branch develop e após isso poderá ser removida. Uma vez pronta a Feature será criada uma Branch Release para que essa novo commit não seja adicionado diretamente a Master. Assim, quando a ligação entre a Release for feita a Master, se cria uma tag, uma indicaçãoque contém uma nova versão do projeto e a cada nova tag na MASTER deverá ser feito também uma tag na Develop. Quando ocorre uma bug ou problema na produção, entra em ação a branch do suporte, a HOTFIX, funciona como uma release mas é usada em situações mais críticas, assim, quando uma HotFix é utilizada ela será mergeada diretamente na master, ela deve receber uma tag após o merge e essa tag também deve estar na Develope.


![fluxo](https://user-images.githubusercontent.com/77363425/107585736-8350ff00-6bdd-11eb-9151-d2d0b2abb6d7.png)

![hotfix](https://user-images.githubusercontent.com/77363425/107585984-e347a580-6bdd-11eb-8152-b37a54f671fa.png)




Link de um vídeo explicando sobre : https://www.youtube.com/watch?v=oweffeS8TRc&t=371s
