### ISSUE TITLE
Estudar o que é TDB

### ISSUE THREAD

**Issue by ciro-c** [fga-eps-mds/2020.2-e-Vacina-Backend#9]
#O que fazer

- [x] Estudar o que é TDB git
- [x] Apresentar par o grupo o que é

**Comment by edsondearaujo** [comment]
Oi, grupo. Eu e a [Geise](https://github.com/GeiseSaunier) vamos acompanhar vocês durante o semestre e ajudá-los conforme for necessário. Aproveito para deixar o link de uma leitura rápida sobre Trunk-based Development (TBD) e GitFlow. Espero que o artigo seja um bom ponta pé inicial nos estudos de TBD do grupo.
- [Trunk-based Development vs. Git Flow](https://www.toptal.com/software/trunk-based-development-git-flow)

**Comment by ggomesbr** [comment]
A sigla TBD significa Trunk-based Development e, assim como o Git Flow, trata-se de um metodo de desenvolvimento de software. Como ja vimos um pouco sobre o GitFlow, a melhor forma que pensei para explicar o TBD foi comparando os dois, enquanto o GitFlow funciona com a utilizacao de branchs, que posteriormente sao "acopladas" (merge) ao codigo principal, que possui um acesso mais restrito. Isto pode abrir uma margem maior a problemas como conflitos de merge e commits muito grandes, ja no TBD e utilizada uma tecnica de "tronco", em que os desenvolvedores trabalham diretamente no tronco do projeto, ou seja, o codigo fonte, utilizando de "flags", que servem para marcar as partes que estao sendo modificadas/adicionadas, podendo deixar estas ativas ou nao.
